/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.ImageIcon;



/**
 *
 * @author Geryes
 */
public class Table extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form Table
     */
    static ViewLogic view;
    
    public Table(ViewLogic v) {
        initComponents();
        view = v;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setForeground(new java.awt.Color(240, 240, 240));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/buttons/new_game_button.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1050, 630, 211, 44);

        jLabel2.setText("Card 1");
        jLabel2.setName(""); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(580, 350, 60, 87);

        jLabel3.setText("Card 2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(650, 350, 60, 87);

        jLabel4.setText("Card 3");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(580, 170, 60, 87);

        jLabel5.setText("Card 4");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(650, 170, 60, 87);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/background.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        view.getShuflled();
        
        String str =  view.getImg(51);
        String str1 = view.getImg(50);
        String str2 = view.getImg(49);
        String str3 = "cardsback.jpg";
        
         ImageIcon cardIcon1 = new ImageIcon(getClass().getResource(str));
         ImageIcon cardIcon2 = new ImageIcon(getClass().getResource(str1));
         ImageIcon cardIcon3 = new ImageIcon(getClass().getResource(str2));
         ImageIcon cardIcon4 = new ImageIcon(getClass().getResource(str3));
         
         jLabel2.setIcon(cardIcon1);
         jLabel3.setIcon(cardIcon2);
         jLabel4.setIcon(cardIcon3);
         jLabel5.setIcon(cardIcon4);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
