/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


public class WelcomeScreen extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	static ViewLogic view;

	private static Table table;

	private String username;
	private String password;
	private String usernameS;
	private String passwordS;
	private String passwordC;

	/**
	 * Creates new form WelcomeScreen
	 * @param v
	 */
	public WelcomeScreen(ViewLogic v) {
		initComponents();
		jPanel1.setVisible(true);
		jPanel2.setVisible(false);
		jPanel2.setEnabled(false);
		view = v;
		this.username = this.password = this.usernameS = this.passwordS = this.passwordC ="";

		//	    JOptionPane.showMessageDialog(this,"Welcome, if this is your first time sign up and start playing :) !" );
		this.repaint();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        usernameT = new javax.swing.JTextField();
        passwordT = new javax.swing.JPasswordField();
        loginB = new javax.swing.JButton();
        signupB = new javax.swing.JButton();
        usernameTs = new javax.swing.JTextField();
        passwordTs = new javax.swing.JPasswordField();
        passwordTc = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        logoutButton = new javax.swing.JButton();
        welcomeText = new javax.swing.JLabel();
        highscoreText = new javax.swing.JLabel();
        winsText = new javax.swing.JLabel();
        totalGamesText = new javax.swing.JLabel();
        percentText = new javax.swing.JLabel();
        playNextGameButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();
        backgroundMain = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(400, 400));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 400));
        jPanel1.setName(""); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        usernameT.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        usernameT.setBorder(null);
        usernameT.setOpaque(false);
        usernameT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameTFocusLost(evt);
            }
        });
        jPanel1.add(usernameT);
        usernameT.setBounds(40, 95, 320, 35);

        passwordT.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        passwordT.setBorder(null);
        passwordT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordTFocusLost(evt);
            }
        });
        jPanel1.add(passwordT);
        passwordT.setBounds(40, 165, 320, 35);

        loginB.setToolTipText("");
        loginB.setBorderPainted(false);
        loginB.setContentAreaFilled(false);
        loginB.setFocusPainted(false);
        loginB.setMaximumSize(new java.awt.Dimension(125, 44));
        loginB.setMinimumSize(new java.awt.Dimension(125, 44));
        loginB.setPreferredSize(new java.awt.Dimension(125, 44));
        loginB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBActionPerformed(evt);
            }
        });
        jPanel1.add(loginB);
        loginB.setBounds(266, 222, 125, 44);

        signupB.setBorderPainted(false);
        signupB.setContentAreaFilled(false);
        signupB.setFocusPainted(false);
        signupB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupBActionPerformed(evt);
            }
        });
        jPanel1.add(signupB);
        signupB.setBounds(705, 295, 119, 44);

        usernameTs.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        usernameTs.setBorder(null);
        usernameTs.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameTsFocusLost(evt);
            }
        });
        jPanel1.add(usernameTs);
        usernameTs.setBounds(475, 95, 320, 35);

        passwordTs.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        passwordTs.setBorder(null);
        passwordTs.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordTsFocusLost(evt);
            }
        });
        jPanel1.add(passwordTs);
        passwordTs.setBounds(475, 165, 320, 35);

        passwordTc.setFont(new java.awt.Font("Times New Roman", 0, 30)); // NOI18N
        passwordTc.setBorder(null);
        passwordTc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordTcFocusLost(evt);
            }
        });
        jPanel1.add(passwordTc);
        passwordTc.setBounds(475, 235, 320, 35);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(220, 130, 850, 370);

        jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel2ComponentShown(evt);
            }
        });
        jPanel2.setLayout(null);

        logoutButton.setBorderPainted(false);
        logoutButton.setContentAreaFilled(false);
        logoutButton.setFocusPainted(false);
        logoutButton.setPreferredSize(new java.awt.Dimension(104, 36));
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        jPanel2.add(logoutButton);
        logoutButton.setBounds(230, 10, 104, 36);

        welcomeText.setFont(new java.awt.Font("Trebuchet MS", 1, 30)); // NOI18N
        welcomeText.setText("Welcome, user:");
        jPanel2.add(welcomeText);
        welcomeText.setBounds(60, 70, 280, 49);

        highscoreText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        highscoreText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        highscoreText.setText("10");
        highscoreText.setPreferredSize(new java.awt.Dimension(35, 15));
        jPanel2.add(highscoreText);
        highscoreText.setBounds(50, 390, 90, 80);

        winsText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        winsText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winsText.setText("2");
        winsText.setPreferredSize(new java.awt.Dimension(35, 15));
        jPanel2.add(winsText);
        winsText.setBounds(150, 390, 80, 80);

        totalGamesText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        totalGamesText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalGamesText.setText("7");
        totalGamesText.setPreferredSize(new java.awt.Dimension(35, 15));
        jPanel2.add(totalGamesText);
        totalGamesText.setBounds(240, 390, 80, 80);

        percentText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        percentText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        percentText.setText("100");
        jPanel2.add(percentText);
        percentText.setBounds(330, 390, 80, 80);

        playNextGameButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/buttons/startGameButton.png"))); // NOI18N
        playNextGameButton.setToolTipText("");
        playNextGameButton.setBorderPainted(false);
        playNextGameButton.setContentAreaFilled(false);
        playNextGameButton.setFocusPainted(false);
        playNextGameButton.setPreferredSize(new java.awt.Dimension(259, 34));
        playNextGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playNextGameButtonActionPerformed(evt);
            }
        });
        jPanel2.add(playNextGameButton);
        playNextGameButton.setBounds(100, 520, 259, 34);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/scorebg.png"))); // NOI18N
        background.setFocusable(false);
        background.setRequestFocusEnabled(false);
        jPanel2.add(background);
        background.setBounds(0, 0, 1280, 720);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(1070, 0, 1280, 720);

        backgroundMain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Loginbg.png"))); // NOI18N
        backgroundMain.setFocusable(false);
        getContentPane().add(backgroundMain);
        backgroundMain.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	/*
	 * Login button action: checks the username and password and according to the result the action is done
	 * opens the User stats panel if the login was successful
	 */

	private void loginBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBActionPerformed
		if(!"".equals(this.username) && !"".equals(this.password)){
			if(view.login(this.username, this.password)){
				//	System.err.println("signin: success welcome  username: " + this.username + " password: " + this.password);
				welcomeText.setText("Welcome " + this.username + " :" );
				welcomeText.setForeground(Color.WHITE);
				this.repaint();
				statsShow();
			}else{
				JOptionPane.showMessageDialog(this,"Username or password are invaild, try again" );
				//	System.err.println("username or passward are invaild");
			}
		}else{
			JOptionPane.showMessageDialog(this,"The fields are blank, fill them and try again" );
			//	System.err.println("the fields are blank try again!");
		}

	}//GEN-LAST:event_loginBActionPerformed


	/*
	 * losing focus function that occur when the username Text lose focus and gets the text to the username
	 */
	private void usernameTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTFocusLost
		this.username = usernameT.getText();
	}//GEN-LAST:event_usernameTFocusLost

	/*
	 * losing focus function that occur when the password Text lose focus and gets the text to the password
	 */
	private void passwordTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTFocusLost
		char[] pass = passwordT.getPassword();
		this.password = new String(pass);
	}//GEN-LAST:event_passwordTFocusLost


	/*
	 * Sign up button action, if the sign up was successful it puts the username and password in the log in fields
	 */
	private void signupBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupBActionPerformed
		if((!"".equals(this.usernameS) && !"".equals(this.passwordS)) && !"".equals(this.passwordC)){
			if(this.passwordS.equals(this.passwordC)){
				if(view.signUp(this.usernameS, this.passwordS)){
					JOptionPane.showMessageDialog(this,"Sign up as < " + this.usernameS  +" > was successful, you can login now!"  );
					//	System.err.println("singup:it was successful  username: " + this.usernameS + " password: " + this.passwordS);
					usernameT.setText(this.usernameS);
					passwordT.setText(this.passwordS);
					this.username = this.usernameS;
					this.password = this.passwordS;
				}else{
					JOptionPane.showMessageDialog(this,"The username < " + this.usernameS  +" > already exists, try again" );
					//	System.err.println("username already exists");
				}
			}else{
				JOptionPane.showMessageDialog(this,"The passwords don't match, try again" );
				//	System.err.println("the password don't match!");
			}
		}else{
			JOptionPane.showMessageDialog(this,"The fields are blank, fill them and try again" );
			//	System.err.println("the fields are blank try again!");
		}

	}//GEN-LAST:event_signupBActionPerformed

	/*
	 * the logout button action, resets the fields
	 */

	private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
		usernameT.setText("");
		passwordT.setText("");
		usernameTs.setText("");
		passwordTs.setText("");
		passwordTc.setText("");
		this.username = this.password = this.usernameS = this.passwordS =  this.passwordC = "";
		jPanel2.setVisible(false);
		jPanel2.setEnabled(false);
		jPanel1.setVisible(true);
		jPanel1.setEnabled(true);

	}//GEN-LAST:event_logoutButtonActionPerformed

	/*
	 * the new game button, transfer the user to the table to play
	 */
	private void playNextGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playNextGameButtonActionPerformed
		view.resetGame();
		table = new Table(view , this , username);
		table.setVisible(true);
		jPanel2.setVisible(false);
		dispose();
	}//GEN-LAST:event_playNextGameButtonActionPerformed

	/*
	 * shown action for panel 2 which is the user stats (to update it)
	 */
	private void jPanel2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2ComponentShown
		fillUserStats();
	}//GEN-LAST:event_jPanel2ComponentShown

	/*
	 * losing focus function that occur when the username (signup side) Text lose focus and gets the text to the username
	 */
	private void usernameTsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameTsFocusLost
		this.usernameS = usernameTs.getText();
	}//GEN-LAST:event_usernameTsFocusLost

	/*
	 * losing focus function that occur when the password (signup side) Text lose focus and gets the text to the password
	 */
	private void passwordTsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTsFocusLost
		char[] pass = passwordTs.getPassword();
		this.passwordS = new String(pass);
	}//GEN-LAST:event_passwordTsFocusLost

	/*
	 * losing focus function that occur when the password confirm (signup side) Text lose focus and gets the text to the password
	 */
	private void passwordTcFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordTcFocusLost
		char[] pass = passwordTc.getPassword();
		this.passwordC = new String(pass);
	}//GEN-LAST:event_passwordTcFocusLost


	/*
	 * brings the user stats from the backend and sets them on screen
	 */
	private void fillUserStats(){

		int d5;
		int d3;
		int d2;
		int d1 = d2 = d3 = d5 = 0;
		double d4 = 0.0;


		d1 = view.userStats(0); //score
		d2 = view.userStats(1); //wins
		d3 = view.userStats(2); // total

		//   System.err.println("inside filluserstats: score " + d1);
		//    System.err.println("inside filluserstats: wins " + d2);
		//    System.err.println("inside filluserstats: total " + d3);
		if(d3 == 0){
			d4 = 0.0;
		}else{
			d4 = d2 /(double) d3;
		}

		d4 = 100*d4 ;
		d5 = (int) d4;


		highscoreText.setText(d1 + "");
		winsText.setText(d2 + "");
		totalGamesText.setText(d3 + "");
		percentText.setText(d5 + "");

		highscoreText.setForeground(Color.WHITE);
		winsText.setForeground(Color.WHITE);
		totalGamesText.setForeground(Color.WHITE);
		percentText.setForeground(Color.WHITE);



	}

	/*
	 * enable the stats panel and show it on screen
	 */

	private void statsShow(){
		jPanel2.setBounds(0, 0, 1280, 720);
		repaint();
		fillUserStats();
		jPanel1.setVisible(false);
		jPanel1.setEnabled(false);
		jPanel2.setVisible(true);
		jPanel2.setEnabled(true);

	}

	/*
	 * jPanel2 getter (the panel for user stats)
	 */

	public JPanel getJpanel2(){
		return this.jPanel2;
	}
	/**
	 * @param args the command line arguments
	 *
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 *
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WelcomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form *
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new WelcomeScreen().setVisible(true);
            }
        });
    }
	 */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel backgroundMain;
    private javax.swing.JLabel highscoreText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginB;
    private javax.swing.JButton logoutButton;
    private javax.swing.JPasswordField passwordT;
    private javax.swing.JPasswordField passwordTc;
    private javax.swing.JPasswordField passwordTs;
    private javax.swing.JLabel percentText;
    private javax.swing.JButton playNextGameButton;
    private javax.swing.JButton signupB;
    private javax.swing.JLabel totalGamesText;
    private javax.swing.JTextField usernameT;
    private javax.swing.JTextField usernameTs;
    private javax.swing.JLabel welcomeText;
    private javax.swing.JLabel winsText;
    // End of variables declaration//GEN-END:variables
}
